export const FETCH_MAIN_REQUEST = 'FETCH_MAIN_REQUEST'
export const FETCH_MAIN_SUCCESS = 'FETCH_MAIN_SUCCESS'
export const FETCH_MAIN_FAILURE = 'FETCH_MAIN_FAILURE'

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_REQUEST'
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'